version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres: